name: CI Check (HTML & Links)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Проверка HTML на ошибки (валидатор)
    - name: HTML Hint
      uses: htmlhint/htmlhint-action@v2
      with:
        target: './*.html'

    # Проверка битых ссылок
    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.9.0
      with:
        args: --verbose ./*.html
